version: "3.9"
services:
    web:
        container_name: server_web
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - db
        networks:
        - mysql-compose-network
    db:
        container_name: videoMonit
        image: mysql:5.7
        restart: always
        environment:
            # MYSQL_DATABASE: 'Server', 'Videos'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'user'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'password'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
        # <Port exposed> : < MySQL Port running inside container>
        - '3306:3306'
        expose:
        # Opens port 3306 on the container
        - '3306'
        # Where our data will be persisted
        volumes:
        - my-db:/var/lib/mysql
        networks:
        - mysql-compose-network
    adminer:
        container_name: adminer
        image: adminer
        ports:
        - 8080:8080
        networks:
        - mysql-compose-network
volumes:
    my-db:

networks: 
  mysql-compose-network:
    driver: bridge